apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genotools-shared-storage
  labels:
    app: genotools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: microk8s-hostpath